# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['d:\video2text'],
    binaries=[],
    datas=[
        ('ai_translator.ico', '.')
    ],
    hiddenimports=[
        # Crypto完整依赖
        'Crypto',
        'Crypto.Cipher',
        'Crypto.Cipher._raw_cbc',
        'Crypto.Cipher._raw_ecb',
        'Crypto.Cipher._raw_cfb',
        'Crypto.Cipher._raw_ofb',
        'Crypto.Cipher._raw_ctr',
        'Crypto.Cipher._raw_aes',
        'Crypto.Cipher._raw_aesni',
        'Crypto.Util',
        'Crypto.Util.Padding',
        'Crypto.Util._raw_api',
        'Crypto.Random',
        'Crypto.Hash',
        'Crypto.Math',
        'Crypto.PublicKey',
        'Crypto.Util.number',
        'Crypto.Util.py3compat',
        
        # cryptography完整依赖
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.bindings',
        'cryptography.hazmat.bindings._rust',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.ciphers.base',
        'cryptography.hazmat.primitives.ciphers.modes',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'cryptography.hazmat.primitives.padding',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.primitives.constant_time',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'cryptography.hazmat.backends.openssl.backend',
        'cryptography.hazmat.primitives.twofactor',
        'cryptography.x509',
        
        # dashscope完整依赖
        'dashscope',
        'dashscope.api_entities',
        'dashscope.api_entities.api_request_factory',
        'dashscope.api_entities.http_request',
        'dashscope.api_entities.encryption',
        'dashscope.api_entities.model_response',
        'dashscope.api_entities.model_request',
        'dashscope.client',
        'dashscope.client.base_api',
        'dashscope.client.http_client',
        'dashscope.aigc',
        'dashscope.aigc.conversation',
        'dashscope.aigc.completion',
        'dashscope.aigc.text_generation',
        'dashscope.common',
        'dashscope.common.error',
        'dashscope.common.utils',
        
        # numpy完整依赖
        'numpy',
        'numpy._core',
        'numpy._core._multiarray_umath',
        'numpy._core._multiarray_tests',
        'numpy._core._dtype_ctypes',
        'numpy._core._type_aliases',
        'numpy._core._exceptions',
        'numpy._core._ufunc_config',
        'numpy._core._add_newdocs',
        'numpy._core._rational',
        'numpy._core._methods',
        'numpy.linalg',
        'numpy.fft',
        'numpy.random',
        
        # matplotlib完整依赖
        'matplotlib',
        'matplotlib.backends',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_qt5',
        'matplotlib.figure',
        'matplotlib.axes',
        'matplotlib.artist',
        'matplotlib.path',
        'matplotlib.spines',
        
        # 网络库完整依赖
        'requests',
        'urllib3',
        'urllib3.util',
        'urllib3.exceptions',
        'urllib3.poolmanager',
        'urllib3.connectionpool',
        'urllib3.connection',
        'urllib3.response',
        'urllib3.request',
        'urllib3.fields',
        'urllib3.filepost',
        'urllib3.contrib',
        'urllib3.contrib.socks',
        'certifi',
        'idna',
        'chardet',
        
        # 项目内部模块
        'module',
        'module.config',
        'module.logger',
        'module.ui',
        'module.window_utils',
        'module.translator_manager',
        'module.translator_unit',
        'module.translation_callback',
        'module.message_center',
        'module.select_language',
        'module.result_recorder',
        'module.network_checker',
        'module.audio_recorder',
        'module.check_authorization',
        'module.info',
        'module.translate_model',
        'module.file_manager',
        'module.config_manager',
        'module.audio_processor',
        'module.video_processor',
        'module.translation_processor'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AI语音实时翻译助手',  # 使用新文件名避免权限冲突
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=['cryptography', 'numpy', 'libcrypto', 'libssl', 'Crypto'],
    include_binaries=True,
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['ai_translator.ico'],
    clean_build=True,
    onefile=True,
    no_temp=False
)
