"""
该模块包含程序内文本翻译的相关信息，定义了语言常量及INFO类，
用于提供多语言文本映射和获取对应翻译文本的功能。
"""
# pylint: disable=too-few-public-methods
# pylint: disable=line-too-long
class INFO:
    """程序内文本翻译映射的类"""
    # 延迟初始化texts字典，避免在导入时就依赖Config
    texts = None

    @classmethod
    def _init_texts(cls):
        """初始化文本字典，在首次使用时调用"""
        if cls.texts is None:
            # 在这里导入Config以避免循环导入
            from .config import Config # pylint: disable=import-outside-toplevel
            cls.texts = {
                Config.LANGUAGE_CHINESE: {
                    "already_stopped_state": "翻译管理器已处于停止状态，无需重复停止操作",
                    "aliyun": "阿里云",
                    "app_not_authorized_message": "未检测到AES授权码 无法运行\n请确保程序在该设备上合法安装",
                    "app_not_authorized_title": "程序未授权",
                    "api_checking": "正在检查API连接...",
                    "api_connection_error": "无法连接到Dashscope API",
                    "api_key_error_message": "API密钥不存在或无效",
                    "api_key_error_title": "API密钥错误",
                    "api_key_lower_phrase": "api_key",
                    "api_key_phrase": "API秘钥",
                    "api_ok": "Dashscope服务器连接成功",
                    "api_reconnect": "连接失败，尝试重试",
                    "audio_api_selection_failed": "警告：选择API失败: {error}",
                    "audio_buffer_full": "音频缓冲区已满，丢弃音频数据",
                    "audio_buffer_process_error": "音频缓冲区处理错误: {error}",
                    "audio_processing_error": "处理音频数据时出错: {error}",
                    "audio_status": "音频状态: {status}",
                    "audio_stream_failed": "打开音频流失败 ({retry}/{max}): {error}",
                    "audio_stream_info": "设备名: {name}, 采样率: {rate} Hz, 通道: {channels}",
                    "audio_transmission_error": "音频传输错误: {error}",
                    "auth_decrypt_failed": "解密失败: {error}",
                    "auth_not_found": "未找到授权信息，可能未正确安装或在未授权设备上运行",
                    "auth_permission_denied": "请以管理员身份运行程序以验证授权",
                    "auth_verify_failed": "授权验证失败: {error}",
                    "baidu": "百度",
                    "backup_device_unavailable": "警告：备用设备 {name} 不可用：{error}",
                    "bing": "必应",
                    "callback_processing_error": "回调处理错误: {error}",
                    "cannot_connect_remote_server": "无法连接到远程服务器",
                    "cannot_start_recording": "警告：无法启动录音",
                    "check_api_key": "请检查API密钥",
                    "check_console_log": "请查看控制台日志获取详细信息",
                    "chinese_language": "中文",
                    "confirm_button": "确定",
                    "connection_check_failed": "连接检查失败: {error}",
                    "connection_failed": "连接失败",
                    "contact_for_help": "请咨询阿里云技术人员",
                    "convert_button": "格式转换",
                    "dashscope_connected": "Dashscope服务器连接成功",
                    "dashscope_unknown_error": "Dashscope发生未知错误: {error}",
                    "device": "设备",
                    "device_invalid": "Device invalid",
                    "device_switch_error": "切换设备时出错: {error}",
                    "dialog_error": "显示错误对话框时出错: {error}",
                    "english_language": "英文",
                    "error": "错误",
                    "error_converting_file": "转换文件",
                    "error_occurred": "时出错",
                    "error_prefix": "错误: {message}",
                    "error_processing_result": "处理结果时出错: {error}",
                    "error_processing_translation": "处理翻译结果出错: {error}",
                    "error_starting_translator": "启动翻译器时出错: ",
                    "error_stopping_translator": "停止翻译器时发生错误: {error}",
                    "file_converted": "文件已转换为{format}格式",
                    "file_conversion_failed": "文件转换失败",
                    "found_sound_device": "找到立体声混音设备",
                    "format_label": "输出格式:",
                    "format_separated": "原译分开",
                    "format_side_by_side": "原译对照",
                    "general_dialog_error": "显示通用错误对话框时出错: {error}",
                    "get_new_key": "请访问阿里云网站获取新的密钥",
                    "have_result": "结果已保存到: ",
                    "http_request_error": "HTTP请求错误",
                    "idle_timeout": "检测到连接超时，正在尝试恢复连接...",
                    "info": "信息",
                    "initialization_error": "初始化错误",
                    "language_file_not_created": "语言设置文件未创建: {path}",
                    "language_save_verify_failed": "语言设置保存验证失败，文件内容不匹配",
                    "language_saved_success": "语言设置已成功保存为: {lang}",
                    "language_verify_error": "验证语言设置时出错: {error}",
                    "load_language_failed": "加载语言设置失败",
                    "loading_remote_api_key": "尝试从远程服务器加载API密钥: {url}",
                    "log_clear_failed": "清空日志文件失败: {error}",
                    "log_close_error": "关闭日志文件时出错: {error}",
                    "log_end": "===== 日志结束 - {timestamp} =====",
                    "log_init_failed": "初始化日志文件失败: {error}",
                    "log_start": "===== 日志开始 - {timestamp} =====",
                    "log_write_failed": "写入日志文件失败: {error}",
                    "mouse_enter_event_error": "鼠标进入事件错误: {error}",
                    "mouse_leave_event_error": "鼠标离开事件错误: {error}",
                    "mouse_move_event_error": "鼠标移动事件错误: {error}",
                    "network_check_timeout": "网络检查超时: {error}",
                    "network_checking": "正在进行网络连接检查...",
                    "network_connection_error": "网络连接错误: {error}",
                    "network_connection_exception": "网络连接异常: 错误类型: {type}, 消息: {message}",
                    "network_disconnected": "网络已断开: {message}",
                    "network_error": "网络连接异常",
                    "network_error_keywords": ["网络错误", "连接断开", "连接关闭", "连接超时", "服务器无响应"],
                    "network_error_message": "网络连接异常，请检查网络连接！",
                    "network_ok": "网络连接正常",
                    "network_recovered": "网络连接已恢复！正在尝试重新连接...",
                    "network_thread_exit_error": "网络检查线程未能正常退出",
                    "no_backup_devices": "警告：没有可用的备用音频设备",
                    "no_error_callback_set": "未设置错误回调函数: {message}",
                    "no_result": "没有翻译结果可保存",
                    "no_result_files": "没有找到翻译结果文件",
                    "no_result_folder": "结果文件夹不存在",
                    "no_translation_result_to_save": "没有翻译结果可保存",
                    "no_valid_api_key_found": "未找到有效的API密钥",
                    "no_valid_api_key_in_remote": "远程文件中未找到符合格式的API密钥",
                    "original_prefix": "原文: ",
                    "original_text_label": "原文",
                    "original_translation_parallel": "原译对照",
                    "original_translation_separate": "原译分开",
                    "partial_files_converted": "{success}/{total}个文件转换为{format}格式\n部分文件转换失败",
                    "processing_thread": "处理线程",
                    "processing_thread_started": "处理线程已启动",
                    "process_error": "处理音频时出错: ",
                    "program_start": "程序启动",
                    "program_stopped": "程序停止",
                    "program_stopped_network": "程序已因网络断开而停止",
                    "prompt": "提示",
                    "recording_failed_max_retries": "录音失败：达到最大重试次数",
                    "recording_stopped": "已停止录音",
                    "recording_stopped_network": "网络断开，已强制停止录音",
                    "recording_stop_error": "录音停止时发生错误: ",
                    "recording_thread_timeout": "录音线程未能在超时时间内终止",
                    "remote_api_key_request_error": "加载远程API密钥时发生请求错误",
                    "remote_api_key_success": "从远程服务器成功获取有效API密钥",
                    "remote_api_key_timeout": "获取远程API密钥超时",
                    "rename_limit_reached": "重命名次数达到上限",
                    "ready_message": "准备就绪",
                    "result_process_thread_started": "结果处理线程启动",
                    "result_thread_not_exited": "警告: 结果处理线程未正常退出",
                    "save_language_failed": "保存语言设置失败",
                    "save_language_retry_failed": "再次尝试保存语言设置失败",
                    "select_audio_api": "选择音频API: {api} (ID: {idx})",
                    "select_language_title": "选择语言",
                    "send_audio_failed": "发送音频失败: {error}",
                    "severe_network_error": "严重网络错误: {message}",
                    "source_lang_label": "源语种:",
                    "source_language": "源语种",
                    "source_language_label": "源语种",
                    "source_target_languages": "源语种: {source}, 目标语种: {target}",
                    "start_button": "开始",
                    "start_message": "请点击开始按钮",
                    "start_recording": "开始录音",
                    "stop_button": "停止",
                    "stop_non_running_translator": "尝试停止未运行的翻译器单元，操作被忽略",
                    "stop_process_error": "停止过程中发生错误: ",
                    "stop_recording": "停止录音",
                    "stopping_program": "正在停止程序",
                    "stereo_mix": "立体声混音",
                    "subtitle_area": "字幕显示区\n拖拽调整窗口位置或大小",
                    "subtitle_update_error": "更新字幕时出错: {error}",
                    "success": "成功",
                    "switch_to_backup_device": "切换到备用设备: {name} (ID: {id})",
                    "target_lang_label": "目标语种:",
                    "target_language": "目标语种",
                    "target_language_label": "目标语种",
                    "thread_not_exited": "{thread_name}未正常退出",
                    "thread_process_stopped": "线程处理已停止",
                    "thread_stopped": "{thread_name}已停止",
                    "translated_prefix": "译文: ",
                    "translated_text_label": "译文",
                    "translation_complete": "翻译已完成",
                    "translation_connection_lost": "翻译连接已断开",
                    "translation_result": "翻译结果",
                    "translation_result_saved_to": "翻译结果保存至: {result_file}",
                    "translation_started": "翻译已开始",
                    "translator_already_stopped": "翻译器组件已处于停止状态，无需再次停止",
                    "translator_start_failed": "启动翻译器失败: {error}",
                    "translator_started": "翻译器已启动",
                    "translator_stop_error": "停止翻译器时出错: {error}",
                    "translator_stopped_success": "翻译器已停止",
                    "ui_method_error": "调用UI方法时出错: {error}",
                    "unexpected_audio_error": "处理音频时发生意外错误: {error}",
                    "unknown_device": "未知设备",
                    "unknown_error": "未知错误",
                    "use_default_audio_api": "使用默认音频API",
                    "use_default_device": "使用默认设备",
                    "use_default_samplerate": "使用默认采样率 {rate} Hz",
                    "use_device_samplerate": "使用设备采样率: {rate} Hz",
                    "use_samplerate": "使用采样率: {rate} Hz",
                    "wait_audio": "等待音频内容",
                    "warning": "警告",
                    "warning_prefix": "警告: {message}",
                    "window_icon_error": "设置窗口图标时发生错误: {error}",
                    "window_title": "AI语音实时翻译助手",
                },
                Config.LANGUAGE_ENGLISH: {
                    "already_stopped_state": "Translation manager is already stopped, duplicate stop operation ignored",
                    "aliyun": "Aliyun",
                    "app_not_authorized_message": "AES authorization code missing or invalid.\nPlease ensure you have a legal installation\non this device.",
                    "app_not_authorized_title": "APP not authorized",
                    "api_checking": "Checking API connection...",
                    "api_connection_error": "Cannot connect to Dashscope API",
                    "api_key_error_message": "API key file missing or invalid.\nPlease ensure there is a TXT file containing a valid\nDashscope API key in the program directory.",
                    "api_key_error_title": "API Key Error",
                    "api_key_lower_phrase": "api_key",
                    "api_key_phrase": "API key",
                    "api_ok": "Dashscope API normal",
                    "api_reconnect": "Connection failed, attempting reconnection",
                    "audio_api_selection_failed": "Warning: Failed to select API: {error}",
                    "audio_buffer_full": "Audio buffer is full, dropping audio data",
                    "audio_buffer_process_error": "Audio buffer processing error: {error}",
                    "audio_processing_error": "Error processing audio data: {error}",
                    "audio_status": "Audio status: {status}",
                    "audio_stream_failed": "Failed to open audio stream ({retry}/{max}): {error}",
                    "audio_stream_info": "Device: {name}, Sample rate: {rate} Hz, Channels: {channels}",
                    "audio_transmission_error": "Audio transmission error: {error}",
                    "auth_decrypt_failed": "Decryption failed: {error}",
                    "auth_not_found": "Authorization information not found, may not be properly installed or running on an unauthorized device",
                    "auth_permission_denied": "Please run the program as administrator to verify authorization",
                    "auth_verify_failed": "Authorization verification failed: {error}",
                    "baidu": "Baidu",
                    "backup_device_unavailable": "Warning: Backup device {name} unavailable: {error}",
                    "bing": "Bing",
                    "callback_processing_error": "Callback processing error: {error}",
                    "cannot_connect_remote_server": "Cannot connect to remote server",
                    "cannot_start_recording": "Warning: Unable to start recording",
                    "check_api_key": "Please check API key",
                    "check_console_log": "Please check the console log for details",
                    "chinese_language": "Chinese",
                    "confirm_button": "OK",
                    "connection_check_failed": "Connection check failed: {error}",
                    "connection_failed": "Connection failed",
                    "contact_for_help": "Please contact Dashscope for technical support",
                    "convert_button": "Convert",
                    "dashscope_connected": "Dashscope server connected successfully",
                    "dashscope_unknown_error": "Unknown Dashscope error: {error}",
                    "dialog_error": "Error displaying error dialog: {error}",
                    "device": "Device",
                    "device_invalid": "Device invalid",
                    "device_switch_error": "Error switching devices: {error}",
                    "english_language": "English",
                    "error": "Error",
                    "error_converting_file": "Error converting file",
                    "error_occurred": "occurred",
                    "error_prefix": "Error: {message}",
                    "error_processing_result": "Error processing result: {error}",
                    "error_processing_translation": "Error processing translation result: {error}",
                    "error_starting_translator": "Error starting translator: ",
                    "error_stopping_translator": "Error stopping translator: {error}",
                    "file_converted": "File converted to {format} format",
                    "file_conversion_failed": "File conversion failed",
                    "found_sound_device": "Found valid stereo mix device",
                    "format_label": "Output:",
                    "format_separated": "Separated",
                    "format_side_by_side": "Side-by-Side",
                    "general_dialog_error": "Error displaying general error dialog: {error}",
                    "get_new_key": "Please visit Dashscope website to obtain a new API key",
                    "have_result": "result saved to: ",
                    "http_request_error": "HTTP request error",
                    "idle_timeout": "Connection timeout, attempting to restore connection...",
                    "info": "Info",
                    "initialization_error": "Initialization error",
                    "language_file_not_created": "Language setting file not created: {path}",
                    "language_save_verify_failed": "Language setting verification failed, file content mismatch",
                    "language_saved_success": "Language setting saved successfully as: {lang}",
                    "language_verify_error": "Error verifying language setting: {error}",
                    "load_language_failed": "Failed to load language setting",
                    "loading_remote_api_key": "Attempting to load API key from remote server: {url}",
                    "log_clear_failed": "Failed to clear log file: {error}",
                    "log_close_error": "Error closing log file: {error}",
                    "log_end": "===== Log ended - {timestamp} =====",
                    "log_init_failed": "Failed to initialize log file: {error}",
                    "log_start": "===== Log started - {timestamp} =====",
                    "log_write_failed": "Failed to write to log file: {error}",
                    "mouse_enter_event_error": "Mouse enter event error: {error}",
                    "mouse_leave_event_error": "Mouse leave event error: {error}",
                    "mouse_move_event_error": "Mouse move event error: {error}",
                    "network_check_timeout": "Network check timeout: {error}",
                    "network_checking": "Checking network connection...",
                    "network_connection_error": "Network connection error: {error}",
                    "network_connection_exception": "Network connection exception: Error type: {type}, message: {message}",
                    "network_disconnected": "Network disconnected: {message}",
                    "network_error": "Network connection error",
                    "network_error_message": "Network connection error, please check your network!",
                    "network_error_keywords": ["network error", "connection disconnected", "connection closed", "connection timeout", "server unresponsive"],
                    "network_ok": "Network connection normal",
                    "network_recovered": "Network connection recovered, reconnecting...",
                    "network_thread_exit_error": "Network check thread failed to exit properly",
                    "no_backup_devices": "Warning: No available backup audio devices",
                    "no_error_callback_set": "No error callback function set: {message}",
                    "no_result": "No result can be saved",
                    "no_result_files": "No translation result files found",
                    "no_result_folder": "result folder does not exist",
                    "no_translation_result_to_save": "No translation result to save",
                    "no_valid_api_key_found": "No valid API key found",
                    "no_valid_api_key_in_remote": "No valid API key found in remote file",
                    "original_prefix": "Original: ",
                    "original_text_label": "Original",
                    "original_translation_parallel": "Original-Translation Parallel",
                    "original_translation_separate": "Original-Translation Separate",
                    "partial_files_converted": "{success}/{total} files converted to {format} format\nSome files failed to convert",
                    "processing_thread": "Processing Thread",
                    "processing_thread_started": "Processing thread started",
                    "process_error": "Error when processing audio: ",
                    "program_start": "Program started",
                    "program_stopped": "Program stopped",
                    "program_stopped_network": "Program stopped due to network disconnection",
                    "prompt": "Prompt",
                    "recording_failed_max_retries": "Recording failed: Maximum retries reached",
                    "recording_stopped": "Recording stopped",
                    "recording_stopped_network": "Network disconnected, recording stopped forcibly",
                    "recording_stop_error": "Error stopping recording: ",
                    "recording_thread_timeout": "Recording thread failed to terminate within timeout period",
                    "remote_api_key_request_error": "Request error when loading remote API key",
                    "remote_api_key_success": "Successfully obtained valid API key from remote server",
                    "remote_api_key_timeout": "Timeout when fetching remote API key",
                    "rename_limit_reached": "Rename limit reached",
                    "result_process_thread_started": "Result processing thread started",
                    "result_thread_not_exited": "Warning: Result processing thread did not exit properly",
                    "ready_message": "Ready",
                    "save_language_failed": "Failed to save language setting",
                    "save_language_retry_failed": "Failed to save language setting on retry",
                    "select_audio_api": "Selected audio API: {api} (ID: {idx})",
                    "select_language_title": "Select Language",
                    "send_audio_failed": "Failed to send audio: {error}",
                    "severe_network_error": "Severe network error: {message}",
                    "source_lang_label": "Source:",
                    "source_language": "Source Language",
                    "source_language_label": "Source Language",
                    "source_target_languages": "Source language: {source}, Target language: {target}",
                    "start_button": "Start",
                    "start_message": "Click start button",
                    "start_recording": "Start recording",
                    "stereo_mix": "stereo mix",
                    "stop_button": "Stop",
                    "stop_process_error": "Error during stopping process: ",
                    "stop_recording": "Stop recording",
                    "stopping_program": "Stopping program",
                    "stop_non_running_translator": "Stop operation on non-running translator",
                    "success": "Success",
                    "subtitle_area": "Subtitle Window\nDrag to adjust position or size",
                    "subtitle_update_error": "Error updating subtitle: {error}",
                    "switch_to_backup_device": "Switched to backup device: {name} (ID: {id})",
                    "target_lang_label": "Target:",
                    "target_language": "Target Language",
                    "target_language_label": "Target Language",
                    "thread_not_exited": "{thread_name} did not exit normally",
                    "thread_process_stopped": "Thread processing stopped",
                    "thread_stopped": "{thread_name} has stopped",
                    "translated_prefix": "Translation: ",
                    "translated_text_label": "Translation",
                    "translation_complete": "Translation complete",
                    "translation_connection_lost": "Translation connection lost",
                    "translation_result": "Translation result",
                    "translation_result_saved_to": "Translation result saved to: {result_file}",
                    "translation_started": "Translation started",
                    "translator_already_stopped": "Translator component is already stopped, no need to stop again",
                    "translator_start_failed": "Failed to start translator: {error}",
                    "translator_started": "Translator started",
                    "translator_stop_error": "Error stopping translator: {error}",
                    "translator_stopped_success": "Translator stopped",
                    "ui_method_error": "Error calling UI method: {error}",
                    "unexpected_audio_error": "Unexpected error processing audio: {error}",
                    "unknown_device": "Unknown device",
                    "unknown_error": "Unknown error",
                    "use_default_audio_api": "Using default audio API",
                    "use_default_device": "Use default device",
                    "use_default_samplerate": "Using default sample rate {rate} Hz",
                    "use_device_samplerate": "Using device sample rate: {rate} Hz",
                    "use_samplerate": "Using sample rate: {rate} Hz",
                    "wait_audio": "Waiting for audio signal",
                    "warning": "Warning",
                    "warning_prefix": "Warning: {message}",
                    "window_icon_error": "Error setting window icon: {error}",
                    "window_title": "AI Translator",
                },
                Config.LANGUAGE_JAPANESE: {
                    "already_stopped_state": "翻訳マネージャーはすでに停止状態です。重複した停止操作は無視されます",
                    "aliyun": "アリババクラウド",
                    "app_not_authorized_message": "AESコードエラー\n合法的にインストールされているか確認してください",
                    "app_not_authorized_title": "プログラム認証エラー",
                    "api_checking": "API接続確認中...",
                    "api_connection_error": "Dashscope APIエラー",
                    "api_key_error_message": "APIキーが存在しないか無効です",
                    "api_key_error_title": "APIキーエラー",
                    "api_key_lower_phrase": "api_key",
                    "api_key_phrase": "APIキー",
                    "api_ok": "Dashscopeサーバー接続成功",
                    "api_reconnect": "接続失敗 再試行します",
                    "audio_api_selection_failed": "警告：API選択失敗: {error}",
                    "audio_buffer_full": "オーディオバッファオーバーフロー オーディオデータを破棄します",
                    "audio_buffer_process_error": "オーディオバッファの処理エラー: {error}",
                    "audio_processing_error": "オーディオデータ処理中エラー発生: {error}",
                    "audio_status": "オーディオ状態: {status}",
                    "audio_stream_failed": "オーディオストリームスタート失敗 ({retry}/{max}): {error}",
                    "audio_stream_info": "デバイス名: {name}, サンプリングレート: {rate} Hz, チャンネル: {channels}",
                    "audio_transmission_error": "オーディオ伝送エラー: {error}",
                    "auth_decrypt_failed": "復号化失敗: {error}",
                    "auth_not_found": "認証情報が見つかりません。正しくインストールされていないか、未認証デバイス可能性あり",
                    "auth_permission_denied": "認証を確認するには、管理者権限でプログラムを実行してください",
                    "auth_verify_failed": "認証確認失敗: {error}",
                    "baidu": "バイドゥ",
                    "backup_device_unavailable": "警告：予備デバイス {name} 使用不可：{error}",
                    "bing": "Microsoft Bing",
                    "callback_processing_error": "コールバック処理エラー: {error}",
                    "cannot_connect_remote_server": "リモートサーバー接続不可",
                    "cannot_start_recording": "警告：録音スタート失敗",
                    "check_api_key": "APIキーを確認してください",
                    "check_console_log": "詳細はログをチェックしてください",
                    "chinese_language": "中国語",
                    "confirm_button": "確認",
                    "connection_check_failed": "接続確認失敗: {error}",
                    "connection_failed": "接続失敗",
                    "contact_for_help": "アリババクラウド技術サポートにお問い合わせください",
                    "convert_button": "フォーマット変換",
                    "dashscope_connected": "Dashscopeサーバー接続完了",
                    "dashscope_unknown_error": "Dashscopeで未知のエラー発生: {error}",
                    "device": "デバイス",
                    "device_switch_error": "デバイス切り替え中エラー発生: {error}",
                    "dialog_error": "エラーダイアログの表示中にエラー: {error}",
                    "english_language": "英語",
                    "error": "エラー",
                    "error_converting_file": "ファイル",
                    "error_occurred": "の変換時にエラー発生",
                    "error_processing_result": "結果処理中のエラー: {error}",
                    "error_processing_translation": "翻訳結果の処理中にエラー発生: {error}",
                    "error_prefix": "エラー: {message}",
                    "error_starting_translator": "翻訳機の起動中にエラー発生: ",
                    "error_stopping_translator": "翻訳機の停止中にエラー発生: {error}",
                    "file_converted": "ファイルが{format}形式に変換されました",
                    "file_conversion_failed": "ファイル変換失敗",
                    "found_sound_device": "ステレオミックスデバイス発見",
                    "format_label": "フォーマット:",
                    "format_separated": "原語と訳語を分ける",
                    "format_side_by_side": "原語と訳語を対照表示",
                    "general_dialog_error": "一般エラーダイアログ表示中エラー: {error}",
                    "get_new_key": "アリババクラウドのウェブサイトにアクセスして新しいAPIキーを取得してください",
                    "have_result": "結果が以下のフォルダーに保存されました: ",
                    "http_request_error": "HTTPリクエストエラー",
                    "idle_timeout": "接続タイムアウト検出。接続回復中...",
                    "info": "情報",
                    "initialization_error": "初期化エラー",
                    "language_file_not_created": "言語設定ファイル作成失敗: {path}",
                    "language_save_verify_failed": "言語設定保存失敗 ファイル内容が一致しません",
                    "language_saved_success": "言語設定が {lang} として保存",
                    "language_verify_error": "言語設定の確認中にエラー発生: {error}",
                    "load_language_failed": "言語設定読み込み失敗",
                    "loading_remote_api_key": "リモートサーバーからAPIキー読み込み中: {url}",
                    "log_clear_failed": "ログファイルクリア失敗: {error}",
                    "log_close_error": "ログファイル閉鎖中エラー発生: {error}",
                    "log_end": "===== ログ終了 - {timestamp} =====",
                    "log_init_failed": "ログファイル初期化失敗: {error}",
                    "log_start": "===== ログ開始 - {timestamp} =====",
                    "log_write_failed": "ログファイルへ書き込み失敗: {error}",
                    "mouse_enter_event_error": "マウス進入イベントエラー: {error}",
                    "mouse_leave_event_error": "マウス離脱イベントエラー: {error}",
                    "mouse_move_event_error": "マウス移動イベントエラー: {error}",
                    "network_check_timeout": "ネットワーク確認タイムアウト: {error}",
                    "network_checking": "ネットワーク接続を確認中...",
                    "network_connection_error": "ネットワーク接続エラー: {error}",
                    "network_connection_exception": "ネットワーク接続例外: エラータイプ: {type}, メッセージ: {message}",
                    "network_disconnected": "ネットワークが切断されました: {message}",
                    "network_error": "ネットワーク接続異常",
                    "network_error_keywords": ["ネットワークエラー", "接続切断", "接続閉鎖", "接続タイムアウト", "サーバー無応答"],
                    "network_error_message": "ネットワーク接続異常発生。ネットワーク接続を確認してください！",
                    "network_ok": "ネットワーク接続正常",
                    "network_recovered": "ネットワーク接続回復 再接続中...",
                    "network_thread_exit_error": "ネットワーク確認スレッド終了エラー",
                    "no_backup_devices": "警告：使用可能な予備オーディオデバイスがありません",
                    "no_error_callback_set": "エラーコールバックセットが設定されていません: {message}",
                    "no_result": "保存する翻訳結果がありません",
                    "no_result_files": "翻訳結果ファイルが見つかりません",
                    "no_result_folder": "翻訳結果フォルダーが存在しません",
                    "no_translation_result_to_save": "翻訳結果がありません",
                    "no_valid_api_key_found": "有効なAPIキーが見つかりません",
                    "no_valid_api_key_in_remote": "リモートファイルに形式が適合するAPIキーが見つかりません",
                    "original_prefix": "原文: ",
                    "original_text_label": "原文",
                    "original_translation_parallel": "原語と訳語を対照表示",
                    "original_translation_separate": "原語と訳語を分ける",
                    "partial_files_converted": "{success}/{total}個のファイルが{format}形式に変換されました\n一部ファイル変換失敗",
                    "processing_thread": "処理スレッド",
                    "processing_thread_started": "処理スレッド開始",
                    "process_error": "オーディオ処理中エラー発生: ",
                    "program_start": "プログラム起動",
                    "program_stopped": "プログラム停止",
                    "program_stopped_network": "ネットワーク切断のため、プログラム停止",
                    "prompt": "指示",
                    "recording_failed_max_retries": "録音失敗：最大リトライ回数到達",
                    "recording_stopped": "録音停止",
                    "recording_stopped_network": "ネットワーク切断がため、録音強制停止",
                    "recording_stop_error": "録音の停止中にエラー発生: ",
                    "recording_thread_timeout": "録音スレッドがタイムアウト期間内に終了しませんでした",
                    "remote_api_key_request_error": "リモートAPIキー読み込み中にリクエストエラー発生",
                    "remote_api_key_success": "リモートサーバーから有効なAPIキーを取得",
                    "remote_api_key_timeout": "リモートAPIキー取得タイムアウト",
                    "rename_limit_reached": "最大リネーム回数到達",
                    "result_process_thread_started": "翻訳結果処理スレッド開始",
                    "result_thread_not_exited": "警告: 翻訳結果処理スレッド終了エラー",
                    "ready_message": "準備完了",
                    "save_language_failed": "言語設定保存失敗",
                    "save_language_retry_failed": "言語設定保存再試行失敗",
                    "select_audio_api": "オーディオAPIを選択: {api} (ID: {idx})",
                    "select_language_title": "言語選択",
                    "send_audio_failed": "オーディオ送信失敗: {error}",
                    "severe_network_error": "重大なネットワークエラー: {message}",
                    "source_lang_label": "原語:",
                    "source_language": "原語",
                    "source_language_label": "原語",
                    "source_target_languages": "原語: {source}, 対象言語: {target}",
                    "start_button": "開始",
                    "start_message": "開始ボタンをクリックしてください",
                    "start_recording": "録音開始",
                    "stereo_mix": "ステレオミックス",
                    "stop_button": "停止",
                    "stop_non_running_translator": "実行中でない翻訳マネージャーの停止操作が無視されました",
                    "stop_process_error": "停止中エラー発生: ",
                    "stop_recording": "録音停止",
                    "stopping_program": "プログラムを停止中",
                    "success": "成功",
                    "subtitle_area": "字幕表示エリア\nドラッグしてウィンドウの位置またはサイズを調整",
                    "subtitle_update_error": "字幕更新中エラー: {error}",
                    "switch_to_backup_device": "予備デバイスに切り替え: {name} (ID: {id})",
                    "target_lang_label": "対象言語:",
                    "target_language": "対象言語",
                    "target_language_label": "対象言語",
                    "thread_not_exited": "{thread_name}が正常に終了しませんでした",
                    "thread_process_stopped": "スレッド処理停止",
                    "thread_stopped": "{thread_name}停止",
                    "translated_prefix": "訳文: ",
                    "translated_text_label": "訳文",
                    "translation_complete": "翻訳完了",
                    "translation_connection_lost": "翻訳接続が切断されました",
                    "translation_result": "翻訳結果",
                    "translation_result_saved_to": "翻訳結果が保存されました: {result_file}",
                    "translation_started": "翻訳が開始されました",
                    "translator_already_stopped": "翻訳コンポーネントはすでに停止状態です。再度停止する必要はありません",
                    "translator_start_failed": "翻訳機起動失敗: {error}",
                    "translator_started": "翻訳機起動",
                    "translator_stop_error": "翻訳機の停止中エラー発生: {error}",
                    "translator_stopped_success": "翻訳機停止",
                    "ui_method_error": "UIメソッド呼び出しエラー: {error}",
                    "unexpected_audio_error": "オーディオの処理中に予期しないエラー発生: {error}",
                    "unknown_device": "不明なデバイス",
                    "unknown_error": "未知のエラー",
                    "use_default_audio_api": "デフォルトオーディオAPIを使用",
                    "use_default_device": "デフォルトデバイスを使用",
                    "use_default_samplerate": "デフォルトサンプリングレート {rate} Hz を使用",
                    "use_device_samplerate": "デバイスサンプリングレートを使用: {rate} Hz",
                    "use_samplerate": "サンプリングレート: {rate} Hz を使用",
                    "wait_audio": "オーディオコンテンツ待ち",
                    "warning": "警告",
                    "warning_prefix": "警告: {message}",
                    "window_icon_error": "ウィンドウアイコン設定中エラー発生: {error}",
                    "window_title": "音声リアルタイム翻訳AI",
                },
                Config.LANGUAGE_KOREAN: {
                    "already_stopped_state": "번역 관리자는 이미 중지 상태입니다. 중복된 중지 작업은 무시됩니다",
                    "aliyun": "알리바바 클라우드",
                    "app_not_authorized_message": "AES 코드 오류\n정상 설치 여부 확인하세요",
                    "app_not_authorized_title": "프로그램 인증 오류",
                    "api_checking": "API 연결 확인 중...",
                    "api_connection_error": "Dashscope API 오류",
                    "api_key_error_message": "API 키 없음 또는 유효하지 않음",
                    "api_key_error_title": "API 키 오류",
                    "api_key_lower_phrase": "api_key",
                    "api_key_phrase": "API 키",
                    "api_ok": "Dashscope 서버 연결 성공",
                    "api_reconnect": "연결 실패. 재시도 중",
                    "audio_api_selection_failed": "경고: API 선택 실패: {error}",
                    "audio_buffer_full": "오디오 버퍼 오버플로. 데이터 폐기",
                    "audio_buffer_process_error": "오디오 버퍼 처리 오류: {error}",
                    "audio_processing_error": "오디오 처리 중 오류 발생: {error}",
                    "audio_status": "오디오 상태: {status}",
                    "audio_stream_failed": "오디오 스트림 열기 실패 ({retry}/{max}): {error}",
                    "audio_stream_info": "장치명: {name}, 샘플률: {rate} Hz, 채널: {channels}",
                    "audio_transmission_error": "오디오 전송 오류: {error}",
                    "auth_decrypt_failed": "복호화 실패: {error}",
                    "auth_not_found": "인증 정보 없음. 정상 설치되지 않았거나 미인증 장치일 수 있음",
                    "auth_permission_denied": "인증 확인하려면 관리자 권한으로 실행하세요",
                    "auth_verify_failed": "인증 확인 실패: {error}",
                    "baidu": "바이두",
                    "backup_device_unavailable": "경고: 백업 장치 {name} 사용 불가: {error}",
                    "bing": "빙",
                    "callback_processing_error": "콜백 처리 오류: {error}",
                    "cannot_connect_remote_server": "원격 서버 연결 불가",
                    "cannot_start_recording": "경고: 녹음 시작 실패",
                    "check_api_key": "API 키 확인하세요",
                    "check_console_log": "상세는 콘솔 로그 확인",
                    "chinese_language": "중국어",
                    "confirm_button": "확인",
                    "connection_check_failed": "연결 확인 실패: {error}",
                    "connection_failed": "연결 실패",
                    "contact_for_help": "알리바바 클라우드 기술 지원에 문의",
                    "convert_button": "형식 변환",
                    "dashscope_connected": "Dashscope 서버 연결 완료",
                    "dashscope_unknown_error": "Dashscope未知 오류: {error}",
                    "device": "장치",
                    "device_switch_error": "장치 전환 중 오류: {error}",
                    "dialog_error": "오류 대화 상자 표시 중 오류: {error}",
                    "english_language": "영어",
                    "error": "오류",
                    "error_converting_file": "파일",
                    "error_occurred": "변환 시 오류 발생",
                    "error_prefix": "오류: {message}",
                    "error_processing_result": "결과 처리 중 오류: {error}",
                    "error_processing_translation": "번역 결과 처리 중 오류: {error}",
                    "error_starting_translator": "번역기 시작 중 오류 발생: ",
                    "error_stopping_translator": "번역기 중지 중 오류: {error}",
                    "file_converted": "파일 {format} 형식으로 변환됨",
                    "file_conversion_failed": "파일 변환 실패",
                    "found_sound_device": "스테레오 믹스 장치 발견",
                    "format_label": "출력 형식:",
                    "format_separated": "원문과 번역문 분리",
                    "format_side_by_side": "원문과 번역문 대조",
                    "general_dialog_error": "일반 오류 대화 상자 표시 중 오류: {error}",
                    "get_new_key": "알리바바 클라우드에서 새 API 키가져오세요",
                    "have_result": "결과는 다음 폴더에 저장됨: ",
                    "http_request_error": "HTTP 요청 오류",
                    "idle_timeout": "연결 타임아웃 감지. 복구 중...",
                    "info": "정보",
                    "initialization_error": "초기화 오류",
                    "language_file_not_created": "언어 설정 파일 생성 실패: {path}",
                    "language_save_verify_failed": "언어 설정 저장 실패. 파일 내용 불일치",
                    "language_saved_success": "언어 설정 {lang}으로 저장됨",
                    "language_verify_error": "언어 설정 확인 중 오류: {error}",
                    "load_language_failed": "언어 설정 로드 실패",
                    "loading_remote_api_key": "원격 서버에서 API 키 로딩중: {url}",
                    "log_clear_failed": "로그 파일 비우기 실패: {error}",
                    "log_close_error": "로그 파일 닫기 중 오류: {error}",
                    "log_end": "===== 로그 종료 - {timestamp} =====",
                    "log_init_failed": "로그 파일 초기화 실패: {error}",
                    "log_start": "===== 로그 시작 - {timestamp} =====",
                    "log_write_failed": "로그 파일 쓰기 실패: {error}",
                    "mouse_enter_event_error": "마우스 진입 이벤트 오류: {error}",
                    "mouse_leave_event_error": "마우스 나가기 이벤트 오류: {error}",
                    "mouse_move_event_error": "마우스 이동 이벤트 오류: {error}",
                    "network_check_timeout": "네트워크 확인 타임아웃: {error}",
                    "network_checking": "네트워크 연결 확인 중...",
                    "network_connection_error": "네트워크 연결 오류: {error}",
                    "network_connection_exception": "네트워크 연결 예외: 타입: {type}, 메시지: {message}",
                    "network_disconnected": "네트워크 연결 끊김: {message}",
                    "network_error": "네트워크 연결 이상",
                    "network_error_keywords": ["네트워크 오류", "연결 끊김", "연결 닫힘", "연결 타임아웃", "서버 응답 없음"],
                    "network_error_message": "네트워크 연결 이상 발생. 연결 확인하세요!",
                    "network_ok": "네트워크 연결 정상",
                    "network_recovered": "네트워크 연결복구. 재연결 중...",
                    "network_thread_exit_error": "네트워크 확인 스레드 종료 오류",
                    "no_backup_devices": "경고: 사용 가능한 백업 오디오 장치 없음",
                    "no_error_callback_set": "오류 콜백 설정되지 않음: {message}",
                    "no_result": "저장할 번역 결과 없음",
                    "no_result_files": "번역 결과 파일 없음",
                    "no_result_folder": "결과 폴더 없음",
                    "no_translation_result_to_save": "저장할 번역 결과 없음",
                    "no_valid_api_key_found": "유효한 API 키 없음",
                    "no_valid_api_key_in_remote": "원격 파일에 유효한 API 키 없음",
                    "original_prefix": "원문: ",
                    "original_text_label": "원문",
                    "original_translation_parallel": "원문과 번역문 대조",
                    "original_translation_separate": "원문과 번역문 분리",
                    "partial_files_converted": "{success}/{total}개의 파일 {format}으로 변환됨\n일부 파일 변환 실패",
                    "processing_thread": "처리 스레드",
                    "processing_thread_started": "처리 스레드 시작",
                    "process_error": "오디오 처리 중 오류 발생: ",
                    "program_start": "프로그램 시작",
                    "program_stopped": "프로그램 중지",
                    "program_stopped_network": "네트워크 끊김으로 프로그램 중지",
                    "prompt": "프롬프트",
                    "recording_failed_max_retries": "녹음 실패: 최대 재시도 횟수 도달",
                    "recording_stopped": "녹음 중지",
                    "recording_stopped_network": "네트워크 끊김으로 녹음 강제 중지",
                    "recording_stop_error": "녹음 중지 중 오류 발생: ",
                    "recording_thread_timeout": "녹음 스레드가 타임아웃 기간 내에 종료되지 않음",
                    "remote_api_key_request_error": "원격 API 키 로드 중 요청 오류",
                    "remote_api_key_success": "원격 서버에서 유효한 API 키가져오기 성공",
                    "remote_api_key_timeout": "원격 API 키가져오기 타임아웃",
                    "rename_limit_reached": "최대 이름 변경 횟수 도달",
                    "result_process_thread_started": "결과 처리 스레드 시작",
                    "result_thread_not_exited": "경고: 결과 처리 스레드 종료 오류",
                    "ready_message": "준비 완료",
                    "save_language_failed": "언어 설정 저장 실패",
                    "save_language_retry_failed": "언어 설정 저장 재시도 실패",
                    "select_audio_api": "오디오 API 선택: {api} (ID: {idx})",
                    "select_language_title": "언어 선택",
                    "send_audio_failed": "오디오 전송 실패: {error}",
                    "severe_network_error": "심각한 네트워크 오류: {message}",
                    "source_lang_label": "원본 언어:",
                    "source_language": "원본 언어",
                    "source_language_label": "원본 언어",
                    "source_target_languages": "원본: {source}, 대상: {target}",
                    "start_button": "시작",
                    "start_message": "시작 버튼 클릭하세요",
                    "start_recording": "녹음 시작",
                    "stereo_mix": "스테레오 믹스",
                    "stop_button": "중지",
                    "stop_non_running_translator": "실행 중이지 않은 번역기 중지 시도, 작업이 무시됨",
                    "stop_process_error": "중지 과정 중 오류 발생: ",
                    "stop_recording": "녹음 중지",
                    "stopping_program": "프로그램 중지 중",
                    "success": "성공",
                    "subtitle_area": "자막 표시 영역\n드래그하여 창 위치/크기 조정",
                    "subtitle_update_error": "자막 업데이트 중 오류: {error}",
                    "switch_to_backup_device": "백업 장치로 전환: {name} (ID: {id})",
                    "target_lang_label": "대상 언어:",
                    "target_language": "대상 언어",
                    "target_language_label": "대상 언어",
                    "thread_not_exited": "{thread_name} 정상 종료되지 않음",
                    "thread_process_stopped": "스레드 처리 중지",
                    "thread_stopped": "{thread_name} 중지",
                    "translated_prefix": "번역문: ",
                    "translated_text_label": "번역문",
                    "translation_complete": "번역 완료",
                    "translation_connection_lost": "번역 연결 끊김",
                    "translation_result": "번역 결과",
                    "translation_result_saved_to": "번역 결과 다음 위치에 저장됨: {result_file}",
                    "translation_started": "번역 시작",
                    "translator_already_stopped": "번역 컴포넌트가 이미 중지 상태입니다. 다시 중지할 필요 없습니다",
                    "translator_start_failed": "번역기 시작 실패: {error}",
                    "translator_started": "번역기 시작",
                    "translator_stop_error": "번역기 중지 중 오류: {error}",
                    "translator_stopped_success": "번역기 중지",
                    "ui_method_error": "UI 메소드 호출 오류: {error}",
                    "unexpected_audio_error": "오디오 처리 중 예기치 않은 오류: {error}",
                    "unknown_device": "알 수 없는 장치",
                    "unknown_error": "알 수 없는 오류",
                    "use_default_audio_api": "기본 오디오 API 사용",
                    "use_default_device": "기본 장치 사용",
                    "use_default_samplerate": "기본 샘플률 {rate} Hz 사용",
                    "use_device_samplerate": "장치 샘플률 사용: {rate} Hz",
                    "use_samplerate": "샘플률 사용: {rate} Hz",
                    "wait_audio": "오디오 내용 대기 중",
                    "warning": "경고",
                    "warning_prefix": "경고: {message}",
                    "window_icon_error": "창 아이콘 설정 중 오류: {error}",
                    "window_title": "음성 실시간 번역 AI"
                }
            }

    @classmethod
    def get(cls, key, language=None):
        """获取对应翻译的方法"""
        # 确保文本字典已初始化
        cls._init_texts()

        # 在这里导入Config以避免循环导入
        from .config import Config # pylint: disable=import-outside-toplevel
        if language is None:
            language = Config.LANGUAGE
        default_lang = Config.LANGUAGE_CHINESE
        return cls.texts.get(language, cls.texts.get(default_lang)).get(key, key)
